const constants = {
    ADMIN_SENT: "ADMIN_SENT",
    ADMIN_LOADING: "ADMIN_LOADING",
    ADMIN_SUCCESS: "ADMIN_SUCCESS",
    ADMIN_ERROR: "ADMIN_ERROR",
    ADMIN_ROLES: "ADMIN_ROLES",
    ADMIN_CREATE_CONFIG: "ADMIN_CREATE_CONFIG"
}
export default constants;