const constants = {
    INVENT_GET_ALL: "INVENT_GET_ALL",
    INVENT_GET_PATH: "INVENT_GET_PATH",
    LOADING: "LOADING",
    ADD_LOADING: "ADD_LOADING",
    ADD_DONE: "ADD_DONE",
    ADD_ERROR: "ADD_ERROR",
    CHANGE_LOCATION: "CHANGE_LOCATION",
    INVENT_ERROR: "INVENT_ERROR",
    DONE: "DONE",
    INVENT_ADD: "INVENT_ADD"
}
export default constants;