const constants = {
    LOGIN_SENT: "LOGIN_SENT",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOGIN_LOGOUT: "LOGIN_LOGOUT",
    REFRESH_TOKEN: "REFRESH_TOKEN"
}
export default constants;